### ISSUE TITLE
GridLayoutManager java.lang.IllegalArgumentException: Span count should be at least 1. Provided 0

### ISSUE THREAD

**Issue by szenasimartin** [WSCSports/blaze-sample-android#9]
Hey guys,
I tried to migrate your sdk(0.90.0->1.2.7) in the ecb app and found this exception:
`2024-10-25 10:09:13.384 29780-29780 AndroidRuntime          com...ports.android.blaze.sampleapp  E  FATAL EXCEPTION: main
                                                                                                    Process: com.wscsports.android.blaze.sampleapp, PID: 29780
                                                                                                    java.lang.IllegalArgumentException: Span count should be at least 1. Provided 0
                                                                                                    	at androidx.recyclerview.widget.GridLayoutManager.setSpanCount(GridLayoutManager.java:841)
                                                                                                    	at androidx.recyclerview.widget.GridLayoutManager.<init>(GridLayoutManager.java:88)
                                                                                                    	at com.blaze.blazesdk.k8.invoke(SourceFile:3)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                                                                                    	at com.blaze.blazesdk.features.moments.widgets.grid.BlazeMomentsWidgetGridView.getWidgetLayoutManager(SourceFile:1)
                                                                                                    	at com.blaze.blazesdk.features.moments.widgets.grid.BlazeMomentsWidgetGridView.getWidgetLayoutManager(SourceFile:2)
                                                                                                    	at com.blaze.blazesdk.widgets.ui.BlazeBaseWidget.d(Unknown Source:19)
                                                                                                    	at com.blaze.blazesdk.z1.invoke(SourceFile:2)
                                                                                                    	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                                                                                                    	at com.blaze.blazesdk.features.moments.widgets.base.BlazeBaseMomentsWidget.getAdapter(Unknown Source:2)
                                                                                                    	at com.blaze.blazesdk.widgets.ui.BlazeBaseWidget.c(SourceFile:2)
                                                                                                    	at com.blaze.blazesdk.c3.onChanged(SourceFile:1)
                                                                                                    	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
                                                                                                    	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
                                                                                                    	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
                                                                                                    	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
                                                                                                    	at com.blaze.blazesdk.ml.invoke(SourceFile:1)
                                                                                                    	at com.blaze.blazesdk.nl.onChanged(Unknown Source:2)
                                                                                                    	at androidx.lifecycle.MediatorLiveData$Source.onChanged(MediatorLiveData.java:171)
                                                                                                    	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
                                                                                                    	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
                                                                                                    	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
                                                                                                    	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
                                                                                                    	at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:959)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:232)
                                                                                                    	at android.os.Looper.loop(Looper.java:317)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8592)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)`

Here is a branch to reproduce the issue:
https://github.com/szenasimartin/blaze-sample-android/tree/span-count-exception (I used the ecb prod api key)

**Comment by szenasimartin** [comment]
I just used a wrong widgetLayout
